source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, UserDetailView, UserChangeView, UserPasswordChangeView, CartClearLogoutView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', CartClearLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change'),
]

source/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from api.views import ProductViewSet, OrderViewSet, get_token_view


app_name = 'api'

router = DefaultRouter()
router.register(r'products', ProductViewSet)
router.register(r'orders', OrderViewSet)

urlpatterns = [
    path('get-token/', get_token_view, name='get_token'),
    path('', include(router.urls)),
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from webapp.views import IndexView, ProductView, ProductCreateView, ProductDeleteView, ProductUpdateView,\
    CartCreateView, CartView, CartDeleteView, OrderCreateView_2

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('', IndexView.as_view(), name='index'),
    path('product/<pk>/', ProductView.as_view(), name='product_view'),
    path('add/', ProductCreateView.as_view(), name='product_create'),
    path('product/<pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/<pk>/cart', CartCreateView.as_view(), name='add_to_cart'),
    path('product/<pk>/cart/delete/', CartDeleteView.as_view(), name='delete_from_cart'),
    path('cart/', CartView.as_view(), name='cart_view'),
    path('order/create/', OrderCreateView_2.as_view(), name='order_create')
]

source/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE, verbose_name='User')
    githubprofile = models.URLField(null=True, blank=True, verbose_name='Github profile')
    about = models.TextField(max_length=2000, null=True, blank=True, verbose_name='About')
    profile_pic = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Profile pic')

    class Meta:
        permissions = [
            ("can_view_user_list", "Can view the list of users"),
            ('can_manage_users', 'Can manage users'),
        ]

    def __str__(self):
        return self.user.username + "'s Profile"

source/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django import forms
from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(label='Email', required=True)

    class Meta(UserCreationForm.Meta):
        fields = ['username', 'password1', 'password2',
                  'first_name', 'last_name', 'email']

    def clean(self):
        cleaned_data = super().clean()

        if len(cleaned_data['first_name']) == 0 and len(cleaned_data['last_name']) == 0:
            raise ValidationError("You need to fill at least one of the name fields")

        return cleaned_data



class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="New password", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Confirm password", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Current password", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Passwords are not the same')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Old password is incorrect')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordChangeView, LogoutView
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.contrib.auth import login, get_user_model, update_session_auth_hash
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm, PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from accounts.models import Profile
from webapp.models import Cart, Order


class RegisterView(CreateView):
    model = User
    template_name = 'user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user).save()
        login(self.request, user)
        return redirect('index')


class UserDetailView(UserPassesTestMixin, DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user == self.get_object()

    def get_context_data(self, **kwargs):
        orders = Order.objects.filter(user__id=self.object.id)
        kwargs['orders'] = orders
        return super().get_context_data(**kwargs)


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user == self.get_object()

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        form.save()
        profile_form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)


class UserPasswordChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})


class CartClearLogoutView(LogoutView):
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        cart_ids = request.session.get('cart_ids', [])
        Cart.objects.filter(pk__in=cart_ids).delete()
        return super().dispatch(request, *args, **kwargs)

source/accounts/templates/user_change.html
{% extends 'base.html' %}
{% block title %}Edit personal data{% endblock %}

{% block menu_links %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:detail' user_obj.pk %}">Cancel</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:password_change' %}">Change password</a>
    </li>
{% endblock %}

{% block content %}
    <h1>Edit personal data</h1>
    <form action="{% url 'accounts:change' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/form.html' with form=form fields_only=True %}
        {% include 'partial/form.html' with form=profile_form fields_only=True %}
        <br>
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
    <h1>Register</h1>
    {% include 'partial/form.html' with form_method='post' button_text="Sign up" %}
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block title %}User page{% endblock %}

{% block menu_links %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:change' user_obj.pk %}">Edit</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:password_change'  %}">Change password</a>
    </li>
{% endblock %}

{% block content %}
    <div class="media">
        {% if user_obj.profile.profile_pic %}
            <img src="{{ user_obj.profile.profile_pic.url }}" class="align-self-start mr-3" width="250" height="auto" alt="user picture">
        {% else %}
            <img src="https://vk.com/images/camera_200.png" class="align-self-start mr-3" width="250" height="auto" alt="user picture">
        {% endif %}
        <div class="media-body">
        <h5 class="mt-0">Page of {{ user_obj.get_full_name|default:user_obj.username }}</h5>
        <p>Username: {{ user_obj.username }}</p>
        <p>About: {% if user_obj.profile.about %}{{ user_obj.profile.about }}{% else %}No details :/{% endif %}</p>
        </div>
    </div>
    <hr>
    <h2 class="my-3">Orders of {{ user_obj.username }}:</h2>
    {% for order in orders %}
        <h3 class="mt-4">Order# {{ order.pk }} - {{ order.created_at }}</h3>
        {% for product in order.order_products.all %}
            <b>Product:</b> {{ product.product.name }}<br>
            <b>Amount:</b> {{ product.amount }}<br>
            {% with x=product.product.price y=product.amount %}
                <b>Sum:</b> {{ x|mul:y }}<br><br>
            {% endwith %}
        {% endfor %}
        <b class="mt-2">Total: {{ order.get_total }}</b><br>
        <hr>
    {% endfor %}
    {% if not orders %}
        <p>You haven't made any orders yet</p>
    {% endif %}
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}

{% block title %}Change password{% endblock %}

{% block menu_links %}
    <li class="nav-item">
        <a class="nav-link" href="{% url "accounts:detail" user_obj.pk %}">Cancel</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "accounts:change" user_obj.pk %}">Edit</a>
    </li>
{% endblock %}

{% block content %}
    <h1>Change password</h1>
    {% url "accounts:password_change" as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method="post" button_text='submit' %}
{% endblock %}